collections_config:
  careers:
    sort:
      key: posted_date
      order: desc
  team_members:

_structures:
  nav_links:
    - label: Links
      icon: link
      value:
        label:
        url:
        alt:
        nav_links:
  faqs:
    - label: FAQ
      icon: question_answer
      value:
        question:
        answer_html:
  products:
    - label: Products
      icon: add
      value:
        name:
        label:
        image:
        link:
  links:
    - label: Links
      icon: link
      value:
        url:
        label:
        screenshot_image:
        icon:
  testimonials:
    - label: testimonials
      icon: format_quote
      value:
        testimonial_text:
        name:
        source:
  assets:
    - label: Image
      icon: insert_photo
      value:
        _type: image
        title:
        image:
    - label: Video
      icon: videocam
      value:
        _type: video
        title:
        embed_url:
  images:
    - label: Image
      icon: insert_photo
      value:
        title:
        image:
  hero:
    - label: Image Carousel
      icon: insert_photo
      value:
        _type: image_carousel
        images:
    - label: Image Banner
      icon: insert_photo
      value:
        _type: image_banner
        images:
    - label: Text Banner
      icon: article
      value:
        _type: text_banner
        text_html:
  videos:
    - label: Videos
      icon: videocam
      value:
        title:
        description_html:
        embed_url:
  buttons:
    - label: buttons
      icon:
      value:
        label:
        link:

_editables:
  block:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    underline: true
    link: true
    bulletedlist: true
    numberedlist: true
    code: true
    horizontalrule: true
    image: true
    undo: true
    redo: true

_inputs:    
  title_html:
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      underline: true
      link: true
      code: true
      undo: true
      redo: true
