# Site settings
title: 4pFoods CMS
email: dev@ocupop.com
url: "http://admin.4pfoods.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  team_members:
    output: true
    permalink: /team/:path/
  farmers:
    output: true
    permalink: /farmers/:path/
  events:
    output: true
    permalink: /events/:path/   

defaults:
  - scope:
      type: 'pages'
    values:
      layout: page
  - scope:
      type: 'team_members'
    values:
      layout: team_member
      _options:
        image:
          uploads_dir: "img/uploads/team/"
  - scope:
      type: 'farmers'
    values:
      layout: farmer
      _options:
        featured_image:
          uploads_dir: "img/uploads/farmers/:title"
  - scope:
      type: 'events'
    values:
      layout: event
      _options:
        featured_image:
          uploads_dir: "img/uploads/events/:title"        




# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

# plugins:


  # Cloudcannon Configuration
_array_structures:
  meta:
    - label: Meta Data
      icon: share
      value:
        description:
        image:
  faqs:        
    - question: Question 1
      answer_html: This is an answer...
  products:
    - label: Products
      icon: add
      value:
        name:
        label:
        image:
        link:
  links:
    - label:
      icon:
      value:
        url:
        label:
        screenshot_image:
        icon:        



