# Site settings
title: 4pFoods Website CMS
email: dev@ocupop.com
url: "http://admin.4pfoods.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      type: 'pages'
    values:
      layout: page
      # variable_name: value


# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap


