# Site settings
title: 4pFoods CMS
email: dev@ocupop.com
url: 'http://cms.4pfoods.com'
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:

# Collections
collections:
  team_members:
    output: true
    permalink: /team/:path/
  farmers:
    output: true
    permalink: /farmers/:path/
  events:
    output: true
    permalink: /events/:path/
  careers:
    output: true
    permalink: /careers/:path/
  newsletters:
    output: false
  posts:
    output: true
    permalink: /posts/:title/
  featured_products:
    output: false
  includes:
    output: false

defaults:
  - scope:
      type: 'team_members'
    values:
      layout: team_member
      _options:
        image:
          uploads_dir: 'img/uploads/team/'
  - scope:
      type: 'farmers'
    values:
      layout: farmer
      _options:
        featured_image:
          uploads_dir: 'img/uploads/farmers/:title'
        image:
          uploads_dir: 'img/uploads/farmers/:title'
  - scope:
      type: 'events'
    values:
      layout: event
      _options:
        featured_image:
          uploads_dir: 'img/uploads/events/'
  - scope:
      type: 'careers'
    values:
      layout: careers
  - scope:
      type: 'posts'
    values:
      layout: post
      _options:
        featured_image:
          uploads_dir: 'img/uploads/posts/'
  - scope:
      type: 'newsletters'
    values:
      _options:
        featured_image:
          uploads_dir: 'img/uploads/newsletters/'

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

# plugins:

# Cloudcannon Configuration
_array_structures:
  meta:
    - label: Meta Data
      icon: share
      value:
        description:
        image:
  faqs:
    - label: FAQ
      icon: question_answer
      value:
        question:
        answer_html:
  products:
    - label: Products
      icon: add
      value:
        name:
        label:
        image:
        link:
  links:
    - label: Links
      icon: link
      value:
        url:
        label:
        screenshot_image:
        icon:
  assets:
    - label: Image
      icon: insert_photo
      value:
        _type: image
        title:
        image:
    - label: Video
      icon: videocam
      value:
        _type: video
        title:
        embed_url:
