source "http://rubygems.org"
ruby "2.6.2"
gem "jekyll"
gem 'sassc'
gem 'scss_lint'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  # gem 'replace_regex'
  # gem 'jekyll-archives'
  # gem 'jekyll-contentblocks'
  # gem 'jekyll-feed'
  # gem 'jekyll-lunr-js-search'
end
